// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCN_NCKH.Models.DBModel;

#nullable disable

namespace TCN_NCKH.Migrations
{
    [DbContext(typeof(NghienCuuKhoaHocContext))]
    [Migration("20250611120746_AddKetquathiIdToTraloiSinhvien")]
    partial class AddKetquathiIdToTraloiSinhvien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NguoidungLoai", b =>
                {
                    b.Property<string>("Nguoidungid")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("NGUOIDUNGID")
                        .IsFixedLength();

                    b.Property<byte>("Loainguoidungid")
                        .HasColumnType("tinyint")
                        .HasColumnName("LOAINGUOIDUNGID");

                    b.HasKey("Nguoidungid", "Loainguoidungid")
                        .HasName("PK__NGUOIDUN__B50EA8B510E1284D");

                    b.HasIndex("Loainguoidungid");

                    b.ToTable("NGUOIDUNG_LOAI", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Cauhoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dethiid")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("DETHIID")
                        .IsFixedLength();

                    b.Property<double?>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("DIEM");

                    b.Property<byte?>("Loaicauhoi")
                        .HasColumnType("tinyint")
                        .HasColumnName("LOAICAUHOI");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NOIDUNG");

                    b.HasKey("Id")
                        .HasName("PK__CAUHOI__3214EC270EB3EBE9");

                    b.HasIndex("Dethiid");

                    b.ToTable("CAUHOI", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Dapan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cauhoiid")
                        .HasColumnType("int")
                        .HasColumnName("CAUHOIID");

                    b.Property<bool?>("Dung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DUNG");

                    b.Property<string>("Noidung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NOIDUNG");

                    b.HasKey("Id")
                        .HasName("PK__DAPAN__3214EC2771EC18BD");

                    b.HasIndex("Cauhoiid");

                    b.ToTable("DAPAN", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Dethi", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<string>("Monhocid")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("MONHOCID")
                        .IsFixedLength();

                    b.Property<DateTime?>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nguoitao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("NGUOITAO")
                        .IsFixedLength();

                    b.Property<string>("Tendethi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENDETHI");

                    b.HasKey("Id")
                        .HasName("PK__DETHI__3214EC27318AC9FC");

                    b.HasIndex("Monhocid");

                    b.HasIndex("Nguoitao");

                    b.ToTable("DETHI", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Ketquathi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Diem")
                        .HasColumnType("float")
                        .HasColumnName("DIEM");

                    b.Property<int?>("Lichthiid")
                        .HasColumnType("int")
                        .HasColumnName("LICHTHIID");

                    b.Property<DateTime?>("Ngaythi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTHI")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sinhvienid")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("SINHVIENID")
                        .IsFixedLength();

                    b.Property<int>("Thoigianlam")
                        .HasColumnType("int")
                        .HasColumnName("THOIGIANLAM");

                    b.HasKey("Id")
                        .HasName("PK__KETQUATH__3214EC27512E5456");

                    b.HasIndex("Lichthiid");

                    b.HasIndex("Sinhvienid");

                    b.ToTable("KETQUATHI", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lambai", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dethiid")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<int>("KetquathiId")
                        .HasColumnType("int");

                    b.Property<string>("SinhVienid")
                        .IsRequired()
                        .HasColumnType("char(15)");

                    b.Property<DateTime>("Thoigianbatdau")
                        .HasColumnType("datetime2");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Dethiid");

                    b.HasIndex("KetquathiId");

                    b.HasIndex("SinhVienid");

                    b.ToTable("Lambais");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lichthi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dethiid")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("DETHIID")
                        .IsFixedLength();

                    b.Property<string>("Lophocid")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("LOPHOCID")
                        .IsFixedLength();

                    b.Property<DateTime>("Ngaythi")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTHI");

                    b.Property<int>("Thoigian")
                        .HasColumnType("int")
                        .HasColumnName("THOIGIAN");

                    b.HasKey("Id")
                        .HasName("PK__LICHTHI__3214EC2703F100A0");

                    b.HasIndex("Dethiid");

                    b.HasIndex("Lophocid");

                    b.ToTable("LICHTHI", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Loainguoidung", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("ID");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Id")
                        .HasName("PK__LOAINGUO__3214EC2720455DF2");

                    b.HasIndex(new[] { "Tenloai" }, "UQ__LOAINGUO__BF45B9965D079753")
                        .IsUnique();

                    b.ToTable("LOAINGUOIDUNG", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lophoc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<string>("Tenlop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOP");

                    b.HasKey("Id")
                        .HasName("PK__LOPHOC__3214EC274DD060B7");

                    b.HasIndex(new[] { "Tenlop" }, "UQ__LOPHOC__E100BDB72D7932BE")
                        .IsUnique();

                    b.ToTable("LOPHOC", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Monhoc", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Mota")
                        .HasColumnType("ntext")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenmon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENMON");

                    b.HasKey("Id")
                        .HasName("PK__MONHOC__3214EC275909EA44");

                    b.ToTable("MONHOC", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Nguoidung", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("ID")
                        .IsFixedLength();

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HOTEN");

                    b.Property<byte?>("Loainguoidungid")
                        .HasColumnType("tinyint")
                        .HasColumnName("LOAINGUOIDUNGID");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<DateTime?>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nguoitao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("NGUOITAO")
                        .IsFixedLength();

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<bool?>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Id")
                        .HasName("PK__NGUOIDUN__3214EC274649593C");

                    b.HasIndex("Loainguoidungid");

                    b.HasIndex(new[] { "Email" }, "UQ__NGUOIDUN__161CF724BBA79AFF")
                        .IsUnique();

                    b.HasIndex(new[] { "Sdt" }, "UQ__NGUOIDUN__CA1930A5836D1A22")
                        .IsUnique()
                        .HasFilter("[SDT] IS NOT NULL");

                    b.ToTable("NGUOIDUNG", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Sinhvien", b =>
                {
                    b.Property<string>("Sinhvienid")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("SINHVIENID")
                        .IsFixedLength();

                    b.Property<string>("Lophocid")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("LOPHOCID")
                        .IsFixedLength();

                    b.Property<string>("Msv")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("MSV")
                        .IsFixedLength();

                    b.HasKey("Sinhvienid")
                        .HasName("PK__SINHVIEN__7B422E3A9725E501");

                    b.HasIndex("Lophocid");

                    b.HasIndex(new[] { "Msv" }, "UQ__SINHVIEN__C790E5AD46CF3D3E")
                        .IsUnique();

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.TraloiSinhvien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cauhoiid")
                        .HasColumnType("int")
                        .HasColumnName("CAUHOIID");

                    b.Property<int?>("Dapanid")
                        .HasColumnType("int")
                        .HasColumnName("DAPANID");

                    b.Property<int?>("KetquathiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaytraloi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTRALOI")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sinhvienid")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("char(15)")
                        .HasColumnName("SINHVIENID")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__TRALOI_S__3214EC2731C5707F");

                    b.HasIndex("Cauhoiid");

                    b.HasIndex("Dapanid");

                    b.HasIndex("KetquathiId");

                    b.HasIndex("Sinhvienid");

                    b.ToTable("TRALOI_SINHVIEN", (string)null);
                });

            modelBuilder.Entity("NguoidungLoai", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Loainguoidung", null)
                        .WithMany()
                        .HasForeignKey("Loainguoidungid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NGUOIDUNG__LOAIN__44FF419A");

                    b.HasOne("TCN_NCKH.Models.DBModel.Nguoidung", null)
                        .WithMany()
                        .HasForeignKey("Nguoidungid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__NGUOIDUNG__NGUOI__440B1D61");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Cauhoi", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Dethi", "Dethi")
                        .WithMany("Cauhois")
                        .HasForeignKey("Dethiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__CAUHOI__DETHIID__2E1BDC42");

                    b.Navigation("Dethi");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Dapan", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Cauhoi", "Cauhoi")
                        .WithMany("Dapans")
                        .HasForeignKey("Cauhoiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__DAPAN__CAUHOIID__31EC6D26");

                    b.Navigation("Cauhoi");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Dethi", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Monhoc", "Monhoc")
                        .WithMany("Dethis")
                        .HasForeignKey("Monhocid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__DETHI__MONHOCID__29572725");

                    b.HasOne("TCN_NCKH.Models.DBModel.Nguoidung", "NguoitaoNavigation")
                        .WithMany("Dethis")
                        .HasForeignKey("Nguoitao")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__DETHI__NGUOITAO__2A4B4B5E");

                    b.Navigation("Monhoc");

                    b.Navigation("NguoitaoNavigation");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Ketquathi", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Lichthi", "Lichthi")
                        .WithMany("Ketquathis")
                        .HasForeignKey("Lichthiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__KETQUATHI__LICHT__403A8C7D");

                    b.HasOne("TCN_NCKH.Models.DBModel.Sinhvien", "Sinhvien")
                        .WithMany("Ketquathis")
                        .HasForeignKey("Sinhvienid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__KETQUATHI__SINHV__3F466844");

                    b.Navigation("Lichthi");

                    b.Navigation("Sinhvien");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lambai", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Dethi", "Dethi")
                        .WithMany()
                        .HasForeignKey("Dethiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCN_NCKH.Models.DBModel.Ketquathi", "Ketquathi")
                        .WithMany()
                        .HasForeignKey("KetquathiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCN_NCKH.Models.DBModel.Sinhvien", "Sinhvien")
                        .WithMany()
                        .HasForeignKey("SinhVienid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dethi");

                    b.Navigation("Ketquathi");

                    b.Navigation("Sinhvien");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lichthi", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Dethi", "Dethi")
                        .WithMany("Lichthis")
                        .HasForeignKey("Dethiid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__LICHTHI__DETHIID__3B75D760");

                    b.HasOne("TCN_NCKH.Models.DBModel.Lophoc", "Lophoc")
                        .WithMany("Lichthis")
                        .HasForeignKey("Lophocid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__LICHTHI__LOPHOCI__3C69FB99");

                    b.Navigation("Dethi");

                    b.Navigation("Lophoc");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Nguoidung", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Loainguoidung", "Loainguoidung")
                        .WithMany("Nguoidungs")
                        .HasForeignKey("Loainguoidungid")
                        .HasConstraintName("FK__NGUOIDUNG__LOAIN__173876EA");

                    b.Navigation("Loainguoidung");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Sinhvien", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Lophoc", "Lophoc")
                        .WithMany("Sinhviens")
                        .HasForeignKey("Lophocid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__SINHVIEN__LOPHOC__239E4DCF");

                    b.HasOne("TCN_NCKH.Models.DBModel.Nguoidung", "SinhvienNavigation")
                        .WithOne("Sinhvien")
                        .HasForeignKey("TCN_NCKH.Models.DBModel.Sinhvien", "Sinhvienid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SINHVIEN__SINHVI__22AA2996");

                    b.Navigation("Lophoc");

                    b.Navigation("SinhvienNavigation");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.TraloiSinhvien", b =>
                {
                    b.HasOne("TCN_NCKH.Models.DBModel.Cauhoi", "Cauhoi")
                        .WithMany("TraloiSinhviens")
                        .HasForeignKey("Cauhoiid")
                        .HasConstraintName("FK__TRALOI_SI__CAUHO__36B12243");

                    b.HasOne("TCN_NCKH.Models.DBModel.Dapan", "Dapan")
                        .WithMany("TraloiSinhviens")
                        .HasForeignKey("Dapanid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__TRALOI_SI__DAPAN__37A5467C");

                    b.HasOne("TCN_NCKH.Models.DBModel.Ketquathi", "Ketquathi")
                        .WithMany("TraloiSinhviens")
                        .HasForeignKey("KetquathiId");

                    b.HasOne("TCN_NCKH.Models.DBModel.Sinhvien", "Sinhvien")
                        .WithMany("TraloiSinhviens")
                        .HasForeignKey("Sinhvienid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__TRALOI_SI__SINHV__35BCFE0A");

                    b.Navigation("Cauhoi");

                    b.Navigation("Dapan");

                    b.Navigation("Ketquathi");

                    b.Navigation("Sinhvien");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Cauhoi", b =>
                {
                    b.Navigation("Dapans");

                    b.Navigation("TraloiSinhviens");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Dapan", b =>
                {
                    b.Navigation("TraloiSinhviens");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Dethi", b =>
                {
                    b.Navigation("Cauhois");

                    b.Navigation("Lichthis");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Ketquathi", b =>
                {
                    b.Navigation("TraloiSinhviens");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lichthi", b =>
                {
                    b.Navigation("Ketquathis");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Loainguoidung", b =>
                {
                    b.Navigation("Nguoidungs");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Lophoc", b =>
                {
                    b.Navigation("Lichthis");

                    b.Navigation("Sinhviens");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Monhoc", b =>
                {
                    b.Navigation("Dethis");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Nguoidung", b =>
                {
                    b.Navigation("Dethis");

                    b.Navigation("Sinhvien");
                });

            modelBuilder.Entity("TCN_NCKH.Models.DBModel.Sinhvien", b =>
                {
                    b.Navigation("Ketquathis");

                    b.Navigation("TraloiSinhviens");
                });
#pragma warning restore 612, 618
        }
    }
}
